#!/bin/bash
# Configuration Guide for XYZ Classic Panorama Auto-Update

echo "📦 XYZ Classic Panorama - Auto-Update Setup Guide"
echo "================================================="
echo ""
echo "Step 1: Add your resource pack files"
echo "  - Place all texture files in: assets/"
echo "  - Keep pack.mcmeta in the root"
echo ""
echo "Step 2: Configure GitHub Secrets"
echo "  Go to: Settings → Secrets and variables → Actions"
echo ""
echo "  Required secrets:"
echo "  - MODRINTH_API_TOKEN"
echo "    Get from: https://modrinth.com/settings/account (API token)"
echo ""
echo "  - MODRINTH_PROJECT_ID"
echo "    Get from: Your Modrinth project page (project slug or UUID)"
echo "    Example: 'xyz-classic-panorama' or 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'"
echo ""
echo "Step 3: Verify workflow permissions"
echo "  Go to: Settings → Actions → General"
echo "  Ensure 'Read and write permissions' is enabled"
echo ""
echo "Step 4: Test the workflow"
echo "  Go to: Actions → Auto-Update Minecraft Resource Pack"
echo "  Click: Run workflow → Run workflow (manual trigger)"
echo ""
echo "How it works:"
echo "  ✓ Daily at 3 AM UTC (configurable in .github/workflows/auto-update.yml)"
echo "  ✓ Fetches latest Minecraft releases from Mojang"
echo "  ✓ Compares against existing Modrinth versions"
echo "  ✓ Auto-updates pack.mcmeta with correct pack_format"
echo "  ✓ Zips and uploads missing versions to Modrinth"
echo "  ✓ No duplicates - skips already uploaded versions"
echo ""
echo "To manually trigger:"
echo "  Actions → Auto-Update Minecraft Resource Pack → Run workflow"
echo ""
echo "✅ Setup complete! The resource pack will auto-update daily."
